In [3]:
import pandas as pd
import os

In [12]:
colegios_publicos_data = pd.read_csv("../data/colegios-publicos.csv", sep =';')
escuelas_infantiles_data = pd.read_csv ("../data/escuelas-infantiles.csv", sep =';')
bicimad_data = pd.read_json("../data/bicimad.json")

In [11]:
os.listdir("../data/")

['.DS_Store',
 'bicimad.json',
 'colegios-publicos.csv',
 'escuelas-infantiles.csv']

In [17]:
bicimad_data.head()

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]"
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]"
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]"
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]"

In [18]:
escuelas_infantiles_data.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,58241,Escuela infantil municipal Agua Dulce,NaN,NaN,Horario ampliado. Comedor.,"BUS: 44 , 128",ENSEÑANZA: Educación Infantil (Primer Ciclo),0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,LEÑEROS,...,TETUAN,439852,4478398,40.454061,-3.709371,914 594 049,NaN,eiaguadulce@madrid.es,/contenido/entidadesYorganismos/CentrosEducaci...,
1,4549323,Escuela infantil municipal Altair,NaN,NaN,NaN,"BUS: 34, 117, 155",ENSEÑANZA: Educación infantil (Primer ciclo),0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,JOSE DE CADALSO,...,LATINA,434748,4470012,40.378132,-3.768701,917 652 101,NaN,eialtair@madrid.es,/contenido/entidadesYorganismos/CentrosEducaci...,
2,5299172,Escuela infantil municipal Amanecer,NaN,NaN,NaN,"METRO: San Cipriano, Puerta de Arganda BUS: 4,...",ENSEÑANZA: Educación infantil (Primer Ciclo).,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,TITANIO,...,VICALVARO,448997,4472549,40.401990,-3.601044,917 765 069,NaN,eiamanecer@madrid.es,/contenido/entidadesYorganismos/CentrosEducaci...,
3,5633312,Escuela infantil municipal Ana de Austria,NaN,NaN,Educación de 0 a 3 años,"BUS: 172, 173",ENSEÑANZA: Educación infantil (Primer ciclo),0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ANA DE AUSTRIA,...,HORTALEZA,444433,4482965,40.495522,-3.655737,917 500 832,NaN,eianadeaustria@madrid.es,/contenido/entidadesYorganismos/CentrosEducaci...,
4,4724002,Escuela infantil municipal Campanilla,NaN,NaN,NaN,"METRO: Alvarado BUS: 124, 128, 3, 64, 66,772, L1",ENSEÑANZA: Educación infantil (Primer Ciclo),0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,AVILA,...,TETUAN,440475,4478241,40.452700,-3.701998,915 707 576,NaN,eicampanilla@madrid.es,/contenido/entidadesYorganismos/CentrosEducaci...,

In [19]:
colegios_publicos_data.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,176850,Colegio Público Adolfo Suárez,NaN,NaN,Comedor - Horario ampliado - Planes de mejora.,BUS: 174,ENSEÑANZAS: Segundo ciclo de E. Infantil - Pri...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,INFANTA CATALINA MICAELA,...,HORTALEZA,444807,4482402,40.488603,-3.652554,917 502 058 / 676 562 792,917 502 058,NaN,/contenido/entidadesYorganismos/CentrosEducaci...,
1,5075,Colegio Público Agustina Díez,NaN,NaN,Comedor - Horario ampliado,"METRO: Alto del Arenal BUS: 54 , 58 , 103 , 143",ENSEÑANZA: Educación infantil - Primaria,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VESUBIO,...,PUENTE DE VALLECAS,445067,4471046,40.388191,-3.647237,917 770 073,917 770 073,NaN,/contenido/entidadesYorganismos/CentrosEducaci...,
2,4693138,Colegio Público Agustín Rodriguez Sahagún,NaN,NaN,Horario ampliado - Comedor - Planes de mejora,Bus: 142,ENSEÑANZA: Educacion Infantil - Primaria - Ens...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,LA GRANJA DE SAN ILDEFONSO,...,VILLA DE VALLECAS,447178,4468793,40.368040,-3.622168,913 324 348,914 941 475,NaN,/contenido/entidadesYorganismos/CentrosEducaci...,
3,5076,Colegio Público Alberto Alcocer,NaN,NaN,Comedor - Transporte - Horario ampliado - Plan...,"METRO: Las Musas BUS: 38 , 48 , 140, 153",ENSEÑANZA: Educación Infantil - Primaria - Ens...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CANILLEJAS A VICALVARO,...,SAN BLAS-CANILLEJAS,448087,4476035,40.433338,-3.612052,913 202 609,913 200 446,NaN,/contenido/entidadesYorganismos/CentrosEducaci...,
4,5077,Colegio Público Alcalde de Móstoles,NaN,NaN,Transporte - Comedor - Horario ampliado - Plan...,"BUS: 34 , 39 , 139 , 117 , 17 ,",ENSEÑANZA: Educación Infantil - Primaria,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ALDEANUEVA DE LA VERA,...,LATINA,434091,4470207,40.379837,-3.776448,917 055 465,915 095 129,NaN,/contenido/entidadesYorganismos/CentrosEducaci...,